openapi: "3.0.3"

info:
  title: DRF Social Oauth2 API Definitions
  version: "1.1.3"

servers:
  - url: http://127.0.0.1:8000

paths:

  /auth/follow-feed/:

    post:
      summary: Creates a new authentication token.
      tags:
        - token
      requestBody:
        description: Body of the convert token request.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConvertToken'
      responses:
        200:
          description: Valid conver token response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The success message.

  schemas:

    ConvertToken:
      description: The definition of a Convert Token request.
      required:
        - followed_by
        - feed_url
      properties:
        grant_type:
          description: The type of the token.
          type: string
          example: "convert_token"
        client_id:
          description: The client id created at Application level in the Django Admin Dashboard.
          type: string
          example: "4P1BfkLBGUaHZNLjgHMJOChwuFC7C22bmHVVkmo"
        client_secret:
          description: The client secret created at Application level in the Django Admin Dashboard.
          type: string
          example: "lxgUAsfHVZztbBXmD9vnssazOM7fp17BV7C3noHh5kMnHkPRLXQ8Bg9ljnANxo2PiF4jSVmJZRynlP5LDsLvt0746QfNof8suw5fdMMNeSOnSrYHM40RzgdCxFQEqtCd"
        backend:
          description: The backend you are authenticating against.
          type: string
          example: "facebook"
        token:
          description: |
            The Access Token generated by the API of the backend. For instance, if you are authenticating with Facebook,
            go to Facebook For Developers  - Graph API Explorer and create an access token for you.
          type: string
          example: |
          "EAAxWEZCUZCn7ABAC7Mpo3IP9s3nd2zKMkZAOQOfg5CQfBhiU2DWRZCcZCeDypH12m5GTMHZAmYSUeULnIbZBJZBQMzZC4nndgx
          jQXunDfRGy1zmAxRy7fT5F8Y50CuYDZAH6Gwq5iBQdltF8C0GRZBrJXGTZBiW6ztrvqLq62NEpLEZAWZAMNW3JF6T2U7108ZBWB4
          VcDYtF7AxaSlhtwZDZD"
